{{- $fullName := include "deploy.fullname" . -}}
{{- range $key, $service := index .Values "services" }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ $fullName }}-{{ $key }}
spec:
  host: {{ $fullName }}
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
    - name: live
      labels:
        app.kubernetes.io/stage: live
    - name: canary
      labels:
        app.kubernetes.io/stage: canary
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}-{{ $key }}
  labels:
    app.kubernetes.io/name: {{ include "deploy.name" $ }}
    helm.sh/chart: {{ include "deploy.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
spec:
  hosts:
{{ toYaml $service.hosts | indent 4 }}
  gateways:
{{ toYaml $service.gateways | indent 4 }}
  http:
  - name: primary
    route:
    - destination:
        host: {{ $fullName }}
        subset:  live
      weight: 100
    - destination:
        host: {{ $fullName }}-canary
        subset:  canary
      weight: 0
---
{{- end -}}